// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLastCode() {
  return window['go']['json']['JSONFormatter']['GetLastCode']();
}

export function PrettifyJSON(arg1, arg2) {
  return window['go']['json']['JSONFormatter']['PrettifyJSON'](arg1, arg2);
}
