// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLastCode() {
  return window['go']['json']['JSONTools']['GetLastCode']();
}

export function JSONToPHP(arg1) {
  return window['go']['json']['JSONTools']['JSONToPHP'](arg1);
}

export function PHPToJSON(arg1) {
  return window['go']['json']['JSONTools']['PHPToJSON'](arg1);
}

export function PrettifyJSON(arg1, arg2) {
  return window['go']['json']['JSONTools']['PrettifyJSON'](arg1, arg2);
}
