// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {editor} from '../models';

export function GetLastCode():Promise<editor.EditorContent>;

export function JSONToPHP(arg1:string):Promise<string>;

export function PHPToJSON(arg1:string):Promise<string>;

export function PrettifyJSON(arg1:number,arg2:string):Promise<string>;
