// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1) {
  return window['go']['tinker']['Tinker']['ExecuteCommand'](arg1);
}

export function GetLastCode() {
  return window['go']['tinker']['Tinker']['GetLastCode']();
}

export function GetProjectDir() {
  return window['go']['tinker']['Tinker']['GetProjectDir']();
}

export function SetProjectDir(arg1) {
  return window['go']['tinker']['Tinker']['SetProjectDir'](arg1);
}
