// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {editor} from '../models';

export function ExecuteCommand(arg1:string):Promise<string>;

export function GetLastCode():Promise<editor.EditorContent>;
