// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1) {
  return window['go']['tinker']['Tinker']['ExecuteCommand'](arg1);
}

export function GetLastCode(arg1) {
  return window['go']['tinker']['Tinker']['GetLastCode'](arg1);
}
