// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetConfig():Promise<config.AppConfig>;

export function OpenDirectoryDialog():Promise<string>;
