// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteTinkerCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteTinkerCommand'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function PrettifyJSON(arg1, arg2) {
  return window['go']['main']['App']['PrettifyJSON'](arg1, arg2);
}
