// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function CloseTab(arg1:string,arg2:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateProject():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function NewTab(arg1:string):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function RemoveProject(arg1:string):Promise<void>;

export function RenameTab(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetActiveJSONTool(arg1:string):Promise<void>;

export function SetActiveTab(arg1:string,arg2:string):Promise<void>;

export function SetCurrentProject(arg1:string):Promise<void>;

export function UpdateProjectSettings(arg1:string,arg2:config.ProjectConfig):Promise<void>;
