// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTab(arg1, arg2) {
  return window['go']['main']['App']['CloseTab'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateProject() {
  return window['go']['main']['App']['CreateProject']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function NewTab(arg1) {
  return window['go']['main']['App']['NewTab'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RenameTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameTab'](arg1, arg2, arg3);
}

export function SetActiveTab(arg1, arg2) {
  return window['go']['main']['App']['SetActiveTab'](arg1, arg2);
}

export function SetCurrentProject(arg1) {
  return window['go']['main']['App']['SetCurrentProject'](arg1);
}

export function UpdateProjectSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectSettings'](arg1, arg2);
}
