// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteTinkerCommand(arg1) {
  return window['go']['main']['App']['ExecuteTinkerCommand'](arg1);
}

export function GetLastCode() {
  return window['go']['main']['App']['GetLastCode']();
}

export function GetLastJSON() {
  return window['go']['main']['App']['GetLastJSON']();
}

export function GetProjectDir() {
  return window['go']['main']['App']['GetProjectDir']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function PrettifyJSON(arg1, arg2) {
  return window['go']['main']['App']['PrettifyJSON'](arg1, arg2);
}

export function SetProjectDir(arg1) {
  return window['go']['main']['App']['SetProjectDir'](arg1);
}
